meta_product_name: "Recipes To Scrape"
meta_title: "Recipes To Scrape - Scrape Recipes with Le Wagon"
meta_description: "Recipes To Scrape is a website built by Le Wagon to help students learn how to scrape content from a website."
meta_image: "cover.png"
twitter_account: "@pLewagonparis"
